### ISSUE TITLE
[Feature Request] - Keep fold/unfold state

### ISSUE THREAD

**Issue by tramhao** [veeso/tui-realm-treeview#3]
## Description

I use treeview to represent the file tree. When I refresh the treeview, all opened folder will become collapsed. Is there a way to preserve the state of treeview when doing refresh? 

### Changes
1. Have the state saved during refresh, like selected and unfolded.
2. Treeview could have an option to unfold several levels duing initialize.

**Comment by tramhao** [comment]
keep_state solve most my problems. Thanks.

**Comment by veeso** [comment]
Okay, I'm glad you solved it anyway, but for me this feature would be interesting, so I'll keep the issue open. I just have to find the time to work on it 😉

**Comment by tramhao** [comment]
Great. Let me state what I did:
1. When refresh the tree, always select keep_state(true).
2. When I delete a node, I send an keycode::down and move the selected node down, then delete the original node. This way I could refresh and keep the tree open.

**Comment by veeso** [comment]
I'm rewriting the library from scratch to work with tui-realm 1.x; so I can close this issue
