### ISSUE TITLE
[BUG] - upgrade to tuirealm 0.5

### ISSUE THREAD

**Issue by tramhao** [veeso/tui-realm-treeview#4]
## Description

When I upgrade to tui-realm 0.5, treeview cannot compile.

## Steps to reproduce

Upgrade to tuirealm 0.5, this component will not work.

## Expected behaviour

It should work as before, but now it complains two version of tui-realm is used.

## Environment

- OS: Arch linux
- Architecturex x86_64x
- Rust version: 1.53.0
- tui-realm-treeview version 0.2

## Additional information
Thanks.

**Comment by veeso** [comment]
Yep, I totally forgot to update this crate 😅 . 0.2.1 fixes the issue
